# Version of docker-compose
version: '3.7'

# Defines the containers 
services:
  # First project container (can be named anything)
  todoapi:
    # Build parameters for the container
    build: 
      context: .
    ports:
      # Maps ports to be accessed by the app outside of the container
      - "4000:4000"
    volumes:
      - ./config:/app/config
      - ./lib:/app/lib
      - ./priv:/app/priv
      - ./mix.exs:/app/mix.exs
      - ./mix.lock:/app/mix.lock
      - ./test:/app/test
    depends_on:
      # The `todoapidb` container needs to be started before `todoapi` is started
      - todoapidb
    networks:
      - service
      - web
  # Second project container
  todoapidb:
    # Declares which Postres image to use
    image: postgres:11.5
    # Declare a volume to not loose database data when stopping the container
    volumes:
      - apipostgres:/var/lib/postgresql/data
    # Maps port to be accessed by `todoapi` container
    ports:
      - "5480:5432"
    networks:
      - service
# This needs to be declared because `volumes` was used in the `todoapidb` and `todoclientdb` container
# Tells Docker to create a volume on the host machine to maintain data
volumes:
  apipostgres:
networks:
  service:
  web:
    name: shared-web
